import audio from "/assets/images/audio.jpg";
import camera1 from "/assets/images/camera1.jpg";
import camera2 from "/assets/images/camera2.jpg";
import camera3 from "/assets/images/camera3.jpg";
import gaming from "/assets/images/gaming.jpg";
import hero from "/assets/images/hero.png";
import smallHero from "/assets/images/smallHero.png";
import highlightImage1 from "/assets/images/highlightImage1.jpg";
import highlightImage2 from "/assets/images/highlightImage2.jpg";
import highlightImage3 from "/assets/images/highlightImage3.jpg";
import highlightImage4 from "/assets/images/highlightImage4.jpg";
import highlightImage5 from "/assets/images/highlightImage5.jpg";
import highlightImage6 from "/assets/images/highlightImage6.jpg";
import cameracontrol from "/assets/images/cameracontrol.png";
import horsevideo from "/assets/images/horsevideo.png";
import horseFrame from "/assets/images/horseFrame.jpg";
import ios1 from "/assets/images/ios1.jpg";
import ios2 from "/assets/images/ios2.jpg";
import ios3 from "/assets/images/ios3.jpg";
import ios4 from "/assets/images/ios4.jpg";
import ios18 from "/assets/images/ios18.jpg";
import iphone from "/assets/images/iphone16.png";
import iphonePro from "/assets/images/iphone16Pro.jpg";
import model1 from "/assets/images/model1.jpg";
import model2 from "/assets/images/model2.jpg";
import model3 from "/assets/images/model3.jpg";
import model4 from "/assets/images/model4.jpg";
import model5 from "/assets/images/model5.jpg";
import phoneZoom from "/assets/images/phoneZoom.png";
import slider1 from "/assets/images/slider1.jpg";
import slider2 from "/assets/images/slider2.jpg";
import slider3 from "/assets/images/slider3.jpg";
import slider4 from "/assets/images/slider4.jpg";
import titaniumStrength from "/assets/images/titaniumStrength.png";
import zoom from "/assets/images/zoom.png";
import zoomCamera from "/assets/images/zoomCamera.png";
import zoomImage from "/assets/images/zoomImage.jpg";

import apple from "/assets/images/apple.svg";
import bag from "/assets/images/bag.svg";
import pause from "/assets/images/pause.svg";
import play from "/assets/images/play.svg";
import replay from "/assets/images/replay.svg";
import right from "/assets/images/right.svg";
import search from "/assets/images/search.svg";
import watch from "/assets/images/watch.svg";

export const appleImg = apple;
export const bagImg = bag;
export const playImg = play;
export const pauseImg = pause;
export const replayImg = replay;
export const rightImg = right;
export const searchImg = search;
export const watchImg = watch;

export const audioImg = audio;
export const camera1Img = camera1;
export const camera2Img = camera2;
export const camera3Img = camera3;
export const cameracontrolImg = cameracontrol;
export const gamingImg = gaming;
export const heroImg = hero;
export const smallHeroImg = smallHero;
export const highlightImage1Img = highlightImage1;
export const highlightImage2Img = highlightImage2;
export const highlightImage3Img = highlightImage3;
export const highlightImage4Img = highlightImage4;
export const highlightImage5Img = highlightImage5;
export const highlightImage6Img = highlightImage6;
export const horsevideoImg = horsevideo;
export const horseFrameImg = horseFrame;
export const ios1Img = ios1;
export const ios2Img = ios2;
export const ios3Img = ios3;
export const ios4Img = ios4;
export const ios18Img = ios18;
export const iphoneImg = iphone;
export const iphoneProImg = iphonePro;
export const model1Img = model1;
export const model2Img = model2;
export const model3Img = model3;
export const model4Img = model4;
export const model5Img = model5;
export const slider1Img = slider1;
export const slider2Img = slider2;
export const slider3Img = slider3;
export const slider4Img = slider4;
export const titaniumStrengthImg = titaniumStrength;
export const zoomImg = zoom;
export const zoomImageImg = zoomImage;
export const zoomCameraImg = zoomCamera;
export const phoneZoomImg = phoneZoom;
